### ISSUE TITLE
Flash usage with multiple styles

### ISSUE THREAD

**Issue by nuxeh** [Gjorgjevikj/SmoothProgress#1]
Hi, love what you've done here...

However, I have one problem, flash usage... It's OK for using a single style, but any calls to setStyle(), or even calling begin() on two separate "display" objects as a workaround, results in inflated flash usage, which is a pain on an atmega328, for example.

My application has numerous "pages", some of which have one style, some of which have another. Then if I try to print another progress bar of one of these styles (same progress object) on another page, to switch between drawing one of the other style, there's a big penalty, since setStyle must be called, even though there's only two progress bar instances overall.

It makes me think, intuitively, there must be some opportunity for reuse of the generated data.

What do you think?

I can attempt such an improvement, and had a quick look, but before delving any deeper I thought I'd ask.

**Comment by nuxeh** [comment]
In fact, i did some experimentation, with unusual results...

So it seems multiple calls to 'showProgressPct' result in very odd flash usage, generally increasing significantly each time it's called on the same object. But then, after enough times, it goes down, which is odd, to say the least.

```
#define BAR_STYLES_IN_PROGMEM
#include <BarStyle2.h>
...
LCD dispA(lcd, inPROGMEM(barStyle2));
SmoothProgressBar batt(dispA, 6, 10, 0, 0);

```

```
  batt.showProgressPct(50); // 23484K
  batt.showProgressPct(50); // 27174K
  batt.showProgressPct(50); // 30924K (>100%)
  batt.showProgressPct(50); // 19882K .....goes down??
  batt.showProgressPct(50); // 19890K
  batt.showProgressPct(50); // 19898K
```

**Comment by nuxeh** [comment]
Also, it does upload and appear to work, so it's not a bug in platformio.

In fact, it works so well, that it seems i have a viable workaround, repeating `showProgressPct` calls until flash usage goes down. There's definitely something very fishy going on here.

**Comment by nuxeh** [comment]
After some poking, I believe this is to do with C++ templates

**Comment by Gjorgjevikj** [comment]
I am not sure I quite understand the problem you are trying to explain. You are mentioning the flash usage... Each style takes some memory (about 50 bytes if I recall right) in RAM or in FLASH (if defined as inPROGMEM). Yes, templates are used, that results creating a new class while compiling takes place for each different LCD object. The rule of thumb is: do not create more than one LCD object (it should be global) if you are not using more than one physical display connected to the same micro-controller (the library was made as such using templates in order to support simultaneous use of multiple displays). It will work but it will waste memory. Reuse the objects and use dispA.setStyle(xyz) to change the style. I don't think I can recreate the problem I believe you are explaining. At least on my tests having one or multiple calls to spb0.showProgressPct(p1); does not have any significant impact on the compiled size. Can you share more of your code?

**Comment by nuxeh** [comment]
Thanks for looking in to it. Yes, there is a single display, single LCD object, which is global, and the objects are reused.

However, I stripped my code down to a minimal example, and the issue I was seeing previously doesn't seem to appear. So I'll need to spend more time digging deeper, but it seems to me that it could be something odd happening at link time.

Even though this seems to be triggered by SmoothProgress, right now I'd say this verges more towards user error.

**Comment by nuxeh** [comment]
It's probably worth mentioning, that for some reason i was using gcc -O3, which usually causes increased binary size, and also odd behaviour such as this, with frequency of function calls (inlining etc), and seems to not be a great idea on an MCU in any case.
